services:
  - type: web
    name: summarize-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: false