services:
  - type: web
    name: story-quiz
    runtime: python
    plan: free
    buildCommand: "npm run build"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
    autoDeploy: true
    healthCheckPath: /