services:
  - type: web
    name: story-quiz
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --config gunicorn_config.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: MONGO_URI
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: ADMIN_EMAIL
        sync: false
    autoDeploy: true
    healthCheckPath: /test